# MongoDB Default Configuration
default[:mongodb][:dbpath] = '/var/log/mongodb'
default[:mongodb][:logpath] = '/var/log/mongodb/mongodb.log'
default[:mongodb][:bind_ip] = '127.0.0.1'
default[:mongodb][:port] = '27017'
default[:mongodb][:journal] = 'true'
default[:mongodb][:journalCommitInterval] = '100'
default[:mongodb][:cpu] = 'false'
default[:mongodb][:verbose] = 'false'
default[:mongodb][:objcheck] = 'true'
default[:mongodb][:quota] = 'false'
default[:mongodb][:oplog] =  '0'
default[:mongodb][:nocursors] = 'false'
default[:mongodb][:noobjcheck] = 'false'
default[:mongodb][:nohints] = 'false'
default[:mongodb][:nohttpinterface] = 'true'
default[:mongodb][:noscripting] =  'false'
default[:mongodb][:notablescan] = 'false'
default[:mongodb][:noprealloc] = 'false'
default[:mongodb][:nssize] = '16'
default[:mongodb][:mms-token] = 
default[:mongodb][:mms-name] = 
default[:mongodb][:mms-interval] =
default[:mongodb][:slave] = 
default[:mongodb][:source] =
default[:mongodb][:only] =
default[:mongodb][:master] =
default[:mongodb][:pair] =
default[:mongodb][:arbiter] = 
default[:mongodb][:oplogSize] =
default[:mongodb][:opIdMem] =
default[:mongodb][:auth] = 'false'
default[:mongodb][:user] = ''
default[:mongodb][:password] =